### ISSUE TITLE
大佬你好，请问如果母鸡有俩IPV4，可以给小鸡整个独立的IPV4么？谢谢！

### ISSUE THREAD

**Issue by znlsl** [MXCCO/lxdpro#2]
大佬你好，请问如果母鸡有俩IPV4，可以给小鸡整个独立的IPV4么？谢谢！

**Comment by MXCCO** [comment]
如果主机商对mac地址过滤，你没法分但是可以用ipt路由到小鸡内网上

**Comment by znlsl** [comment]
> 如果主机商对mac地址过滤，你没法分但是可以用ipt路由到小鸡内网上

额 其实就是甲骨文的ARM，我想把4+24的虚拟出一个2+12的给群友用，哈哈

**Comment by MXCCO** [comment]
好像arm的不支持
